# Generated by Django 6.0 on 2026-04-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club_app", "0002_equipment_member_trainer_gymclass"),
    ]

    operations = [
        migrations.CreateModel(
            name="DamagedEquipment",
            fields=[],
            options={
                "verbose_name": "Maintenance Alert",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("club_app.equipment",),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gymclass",
            name="base_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="member",
            name="balance",
            field=models.FloatField(),
        ),
    ]
